version: "3.5"

services:
  IoTService:
    container_name: IoTService
    image: iot_service
    build: .
    devices:
      - /dev/bus/usb/001/005:/dev/bus/usb/001/005
      - /dev/gpiomem:/dev/gpiomem
    ports:
      - "632:631"
    restart: unless-stopped
