name: deploy_docker_image_of_backend_service

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    pull_request:
      types: [opened, reopened]
      paths:
        - 'BackendService/**'

jobs:  
    build_docker_image:
        runs-on: ubuntu-latest
        env:
          GITHUB_SHA: ${{ github.sha }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Build Docker image
              run: |
                docker buildx create --use
                docker buildx build \
                  --file ./BackendService/Dockerfile \
                  --tag backend-service:latest \
                  --load \
                  ./BackendService
    
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
            - name: Tag and push Docker image to Docker Hub
              run: |
                docker tag backend-service:latest \
                  ${{ secrets.DOCKER_HUB_USERNAME }}/backend-service:$GITHUB_SHA
                docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend-service:$GITHUB_SHA
            
            - name: Log in to Yandex Cloud Container Registry
              id: login-cr
              uses: yc-actions/yc-cr-login@v1
              with:
                yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
            
            - name: Tag and push Docker image to Yandex Cloud Container Registry
              env:
                  YC_CONTAINER_REGISTRY: ${{ secrets.YC_CONTAINER_REGISTRY }}
                  YC_CONTAINER_REGISTRY_REPO: backend-service
              run: |
                docker tag backend-service:latest cr.yandex/$YC_CONTAINER_REGISTRY/$YC_CONTAINER_REGISTRY_REPO:$GITHUB_SHA
                docker push cr.yandex/$YC_CONTAINER_REGISTRY/$YC_CONTAINER_REGISTRY_REPO:$GITHUB_SHA